---
- hosts: apic
  connection: local
  gather_facts: False
  ignore_errors: yes

  vars:

      validate_certs: false



  tasks:
    - name: Add a new AP
      cisco.aci.aci_ap:
        validate_certs: false
        tenant: "TN-ANDRAS"
        ap: "AP-SEMAPHOREUI1"
        description: default ap
        monitoring_policy: default
        state: present
      delegate_to: localhost
